/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penyakitkucing;

/**
 *
 * @author A S U S
 */
public class DIAGNOSA extends javax.swing.JFrame {

    /**
     * Creates new form DIAGNOSA
     */
    public DIAGNOSA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        km = new javax.swing.JCheckBox();
        bbt = new javax.swing.JCheckBox();
        rb = new javax.swing.JCheckBox();
        m = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        sb = new javax.swing.JCheckBox();
        bc = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        h = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DIAGNOSA");

        km.setText("KULIT MERAH");

        bbt.setText("BERAT BADAN TURUN");

        rb.setText("RONTOK BULU");
        rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActionPerformed(evt);
            }
        });

        m.setText("MUNTAH");
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("CEK HASIL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sb.setText("SERING BAB");

        bc.setText("BAB CAIR");

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jLabel2.setText("KUCING ANDA MENDERITA PENYAKIT :");

        h.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel3.setText("SILAHKAN PILIH GEJALA DI BAWAH INI :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(km)
                            .addComponent(sb)
                            .addComponent(rb))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bc)
                            .addComponent(m)
                            .addComponent(bbt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(km)
                    .addComponent(bbt))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sb)
                    .addComponent(m))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb)
                    .addComponent(bc))
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(h, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mActionPerformed

    private void rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if ((km.isSelected() || rb.isSelected()) || (km.isSelected() && rb.isSelected())) {
            h.setText("KUTU");
            area.setText("GEJALA\n" +
"1 . Gatal berlebihan yang menyebabkan kucing menggaruk \n" +
"2 . Kulit kucing terlihat Memerah\n" +
"3 . Kerontokan bulu, biasanya terjadi di sekitar telinga dan leher.\n" +
"\n" +
"PENYEBAB\n" +
"1. Muncul Perantara Manusia\n" +
"2. Ditularkan Hewan Pengerat\n" +
"\n" +
"MENGOBATI \n" +
"1. Gunakan Sampo Khusus Kucing\n" +
"2. Pakai Obat Kutu");
            
        }
        if ( (sb.isSelected() || bc.isSelected()) || (sb.isSelected() && bc.isSelected()) ) {
            h.setText("DIARE");
            area.setText("GEJALA\n" +
"1 . Lemas\n" +
"2 . Muntah\n" +
"3 . Lesu\n" +
"\n" +
"\n" +
"PENYEBAB\n" +
"1. Infeksi Bakteri Atau Virus\n" +
"2. Minum air yang tidak bersih atu higienis.\n" +
"3. cuaca Tidak Stabil\n" +
"4. Alergi Makanan\n" +
"\n" +
"MENGOBATI \n" +
"1. Bawa Ke dokter Kucing\n" +
"2. Berikan Larutan Elektrolit\n" +
"3. Berikan Obat Anti Diare");
        }
        
        if ( (bbt.isSelected() || m.isSelected()) || (bbt.isSelected() && m.isSelected()) ) {
            h.setText("CACINGAN");
            area.setText("GEJALA\n" +
"1 . Kehilangan berat badan\n" +
"2 . Bulu kering atau kasar\n" +
"3 . Muntah\n" +
"4 . Perut kembung\n" +
"5 . Kelesuan\n" +
"\n" +
"\n" +
"PENYEBAB\n" +
"1. melakukan kontak dengan telur atau feses dari kucing lain yang terinfeksi\n" +
"2. berburu hewan pengerat dan terinfeksi oleh larva cacing yang hidup di jaringan hewan\n" +
"\n" +
"MENGOBATI \n" +
"1. Bawa Ke dokter Kucing\n" +
"2. Berikan obat yang diresepkan kepada kucing");
        }
        
        if ((km.isSelected() && sb.isSelected()) || (km.isSelected() && bc.isSelected())) {
            h.setText("KUTU DAN DIARE");
            area.setText("GEJALA KUTU \n" +
"1 . Gatal berlebihan yang menyebabkan kucing menggaruk \n" +
"2 . Kulit kucing terlihat Memerah\n" +
"3 . Kerontokan bulu, biasanya terjadi di sekitar telinga dan leher.\n" +
"\n" +
"PENYEBAB\n" +
"1. Muncul Perantara Manusia\n" +
"2. Ditularkan Hewan Pengerat\n" +
"\n" +
"MENGOBATI \n" +
"1. Gunakan Sampo Khusus Kucing\n" +
"2. Pakai Obat Kutu\n\n" +

"GEJALA DIARE \n" +
"1 . Lemas\n" +
"2 . Muntah\n" +
"3 . Lesu\n" +
"\n" +
"PENYEBAB\n" +
"1. Infeksi Bakteri Atau Virus\n" +
"2. Minum air yang tidak bersih atu higienis.\n" +
"3. cuaca Tidak Stabil\n" +
"4. Alergi Makanan\n" +
"\n" +
"MENGOBATI \n" +
"1. Bawa Ke dokter Kucing\n" +
"2. Berikan Larutan Elektrolit\n" +
"3. Berikan Obat Anti Diare");
        }
        if ((rb.isSelected() && sb.isSelected()) || (rb.isSelected() && bc.isSelected())) {
            h.setText("KUTU DAN DIARE");
            area.setText("GEJALA KUTU \n" +
"1 . Gatal berlebihan yang menyebabkan kucing menggaruk \n" +
"2 . Kulit kucing terlihat Memerah\n" +
"3 . Kerontokan bulu, biasanya terjadi di sekitar telinga dan leher.\n" +
"\n" +
"PENYEBAB\n" +
"1. Muncul Perantara Manusia\n" +
"2. Ditularkan Hewan Pengerat\n" +
"\n" +
"MENGOBATI \n" +
"1. Gunakan Sampo Khusus Kucing\n" +
"2. Pakai Obat Kutu\n\n" +

"GEJALA DIARE \n" +
"1 . Lemas\n" +
"2 . Muntah\n" +
"3 . Lesu\n" +
"\n" +
"PENYEBAB\n" +
"1. Infeksi Bakteri Atau Virus\n" +
"2. Minum air yang tidak bersih atu higienis.\n" +
"3. cuaca Tidak Stabil\n" +
"4. Alergi Makanan\n" +
"\n" +
"MENGOBATI \n" +
"1. Bawa Ke dokter Kucing\n" +
"2. Berikan Larutan Elektrolit\n" +
"3. Berikan Obat Anti Diare");
        }
        if ((km.isSelected() && bbt.isSelected()) || (km.isSelected() && m.isSelected())) {
            h.setText("KUTU DAN CACINGAN");
            area.setText("GEJALA KUTU \n" +
"1 . Gatal berlebihan yang menyebabkan kucing menggaruk \n" +
"2 . Kulit kucing terlihat Memerah\n" +
"3 . Kerontokan bulu, biasanya terjadi di sekitar telinga dan leher.\n" +
"\n" +
"PENYEBAB\n" +
"1. Muncul Perantara Manusia\n" +
"2. Ditularkan Hewan Pengerat\n" +
"\n" +
"MENGOBATI \n" +
"1. Gunakan Sampo Khusus Kucing\n" +
"2. Pakai Obat Kutu\n\n" +

"GEJALA CACINGAN\n" +
"1 . Kehilangan berat badan\n" +
"2 . Bulu kering atau kasar\n" +
"3 . Muntah\n" +
"4 . Perut kembung\n" +
"5 . Kelesuan\n" +
"\n" +
"\n" +
"PENYEBAB\n" +
"1. melakukan kontak dengan telur atau feses dari kucing lain yang terinfeksi\n" +
"2. berburu hewan pengerat dan terinfeksi oleh larva cacing yang hidup di jaringan hewan\n" +
"\n" +
"MENGOBATI \n" +
"1. Bawa Ke dokter Kucing\n" +
"2. Berikan obat yang diresepkan kepada kucing");
        }
        if ((rb.isSelected() && bbt.isSelected()) || (rb.isSelected() && m.isSelected())) {
            h.setText("KUTU DAN CACINGAN");
            area.setText("GEJALA KUTU \n" +
"1 . Gatal berlebihan yang menyebabkan kucing menggaruk \n" +
"2 . Kulit kucing terlihat Memerah\n" +
"3 . Kerontokan bulu, biasanya terjadi di sekitar telinga dan leher.\n" +
"\n" +
"PENYEBAB\n" +
"1. Muncul Perantara Manusia\n" +
"2. Ditularkan Hewan Pengerat\n" +
"\n" +
"MENGOBATI \n" +
"1. Gunakan Sampo Khusus Kucing\n" +
"2. Pakai Obat Kutu\n\n" +

"GEJALA CACINGAN\n" +
"1 . Kehilangan berat badan\n" +
"2 . Bulu kering atau kasar\n" +
"3 . Muntah\n" +
"4 . Perut kembung\n" +
"5 . Kelesuan\n" +
"\n" +
"\n" +
"PENYEBAB\n" +
"1. melakukan kontak dengan telur atau feses dari kucing lain yang terinfeksi\n" +
"2. berburu hewan pengerat dan terinfeksi oleh larva cacing yang hidup di jaringan hewan\n" +
"\n" +
"MENGOBATI \n" +
"1. Bawa Ke dokter Kucing\n" +
"2. Berikan obat yang diresepkan kepada kucing");
        }
        if ((sb.isSelected() && bbt.isSelected()) || (sb.isSelected() && m.isSelected())) {
            h.setText("DIARE DAN CACINGAN");
            area.setText("GEJALA DIARE\n" +
"1 . Lemas\n" +
"2 . Muntah\n" +
"3 . Lesu\n" +
"\n" +
"\n" +
"PENYEBAB\n" +
"1. Infeksi Bakteri Atau Virus\n" +
"2. Minum air yang tidak bersih atu higienis.\n" +
"3. cuaca Tidak Stabil\n" +
"4. Alergi Makanan\n" +
"\n" +
"MENGOBATI \n" +
"1. Bawa Ke dokter Kucing\n" +
"2. Berikan Larutan Elektrolit\n" +
"3. Berikan Obat Anti Diare\n" +

"GEJALA CACINGAN\n" +
"1 . Kehilangan berat badan\n" +
"2 . Bulu kering atau kasar\n" +
"3 . Muntah\n" +
"4 . Perut kembung\n" +
"5 . Kelesuan\n" +
"\n" +
"\n" +
"PENYEBAB\n" +
"1. melakukan kontak dengan telur atau feses dari kucing lain yang terinfeksi\n" +
"2. berburu hewan pengerat dan terinfeksi oleh larva cacing yang hidup di jaringan hewan\n" +
"\n" +
"MENGOBATI \n" +
"1. Bawa Ke dokter Kucing\n" +
"2. Berikan obat yang diresepkan kepada kucing");
        }
        if ((sb.isSelected() && m.isSelected()) || (sb.isSelected() && bbt.isSelected())) {
            h.setText("DIARE DAN CACINGAN");
            area.setText("GEJALA DIARE\n" +
"1 . Lemas\n" +
"2 . Muntah\n" +
"3 . Lesu\n" +
"\n" +
"\n" +
"PENYEBAB\n" +
"1. Infeksi Bakteri Atau Virus\n" +
"2. Minum air yang tidak bersih atu higienis.\n" +
"3. cuaca Tidak Stabil\n" +
"4. Alergi Makanan\n" +
"\n" +
"MENGOBATI \n" +
"1. Bawa Ke dokter Kucing\n" +
"2. Berikan Larutan Elektrolit\n" +
"3. Berikan Obat Anti Diare\n" +

"GEJALA CACINGAN\n" +
"1 . Kehilangan berat badan\n" +
"2 . Bulu kering atau kasar\n" +
"3 . Muntah\n" +
"4 . Perut kembung\n" +
"5 . Kelesuan\n" +
"\n" +
"\n" +
"PENYEBAB\n" +
"1. melakukan kontak dengan telur atau feses dari kucing lain yang terinfeksi\n" +
"2. berburu hewan pengerat dan terinfeksi oleh larva cacing yang hidup di jaringan hewan\n" +
"\n" +
"MENGOBATI \n" +
"1. Bawa Ke dokter Kucing\n" +
"2. Berikan obat yang diresepkan kepada kucing");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DIAGNOSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DIAGNOSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DIAGNOSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DIAGNOSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DIAGNOSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JCheckBox bbt;
    private javax.swing.JCheckBox bc;
    private javax.swing.JLabel h;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox km;
    private javax.swing.JCheckBox m;
    private javax.swing.JCheckBox rb;
    private javax.swing.JCheckBox sb;
    // End of variables declaration//GEN-END:variables
}
